### ISSUE TITLE
Timer becomes very out of sync when minimized to tray

### ISSUE THREAD

**Issue by ryanbaer** [builtwithluv/ZenFocus#206]
**Environment**
macOS Sierra 10.12.6

**Description**
When minimized to tray, the timer ticks at much slower rate than when the app is open, i.e. each 'in-app' second > actual second. Running an accurate timer alongside this app for 25 minutes resulted in the app finishing **12 minutes later** than the actual elapsed time of 25 minutes.
Interestingly, though perhaps unrelated, it appeared to resume a more accurate tick rate within the final 2 minutes.

**Expected Result**
The timer is accurate to the system clock regardless of window state.

**Comment by chengsieuly** [comment]
Thanks for reporting this! I'll look into it =)

**Comment by chengsieuly** [comment]
Which version was this in?
