### ISSUE TITLE
Switching Phases - Confirmation broken

### ISSUE THREAD

**Issue by gprasant** [builtwithluv/ZenFocus#221]
**Environment**
macOS Sierra 10.12.6
ZenFocus Version 1.4.2

**Description**
With the _"Ask for confirmation before moving on to the next phase"_, the application moves on to the next phase, without waiting for the user to confirm. 

**Observations**
1. Click on the **settings gear**, then **Notifications**.
2. Enable the _"Ask for confirmation before moving on to the next phase"_ setting.
3. Wait for a focus time to elapse. 
4. After the focus time elapses, the timer displays a prompt asking whether to continue, but it also sneaks into the next rest phase. 

![zen_focus](https://user-images.githubusercontent.com/212911/31694940-0f79ab50-b35c-11e7-8e12-d8d4d9b5ac54.gif)

**Expected Result**
1. The timer should be paused till the user selects OK or cancel. 
2. If the user selects "OK", the next phase should resume and the timer should count down.
3. If the user selects Cancel, the next phase should be paused and the timer should **NOT** count down.

**Comment by gprasant** [comment]
Thanks for triaging this issue @chengsieuly . This is important for a couple of reasons. 

1. A user is in a flow of work and abruptly/silently switching the phase to "break" phase is counter-productive. 
2. When a user is taking a break, sometimes the short breaks might be a little longer than the specified interval. In these cases, we do not want the app to automatically switch to the next working phase.

**Comment by chengsieuly** [comment]
Fixed in #222 =). We send out a release this Friday just in case there will be other bugs you and others will find =)

**Comment by gprasant** [comment]
Great!

**Comment by ehguo** [comment]
Lol I guess this is why they write tests, so when stuff gets refactored old stuff doesn't break unnoticed :)

**Comment by chengsieuly** [comment]
Very true @ehguo. We will make it our priority =)
