### ISSUE TITLE
App continues to next phase even when "Ask for Confirmation" is checked.

### ISSUE THREAD

**Issue by drewjbartlett** [builtwithluv/ZenFocus#227]
The app will ask me if I want to continue to the next phase but the phase automatically starts without my approval behind the prompt.

P.S. I love this app! Been looking for a clean UI for this for years!

**Comment by chengsieuly** [comment]
Thanks @drewjbartlett! This issue was addressed here - #221 and will be fixed in the next release which will be tonight! =) Please continue to submit issues and even features/enhancements that you would like to see!

**Comment by drewjbartlett** [comment]
@chengsieuly baller, thanks!
