### ISSUE TITLE
Compact mode keep compact between steps

### ISSUE THREAD

**Issue by jhg** [builtwithluv/ZenFocus#254]
When it pass to the next step it back to normal mode. I think it's useful to keep in compact mode.

**Comment by chengsieuly** [comment]
Does this happen only when you have “ask before going to next phase” on?

Thanks for using the app btw!

**Comment by jhg** [comment]
Si, efectivamente, he probado a desactivar esa opción y aunque pasa de fase sin avisar no sale del modo compacto. Lo unico que tengo que estar atento del color (estoy probandolo en un PC en el que no tengo altavoces ni cascos conectados).

**Comment by chengsieuly** [comment]
Hey @jhg, is this okay now or do you foresee a better way to display warning message while in compact or is setting that setting good enough?
