### ISSUE TITLE
Changing sounds not working on Windows 10

### ISSUE THREAD

**Issue by freekarol** [builtwithluv/ZenFocus#256]
Actually, I can change notification sounds.  But it doesn't matter what sound I add I can always hear just the default one. Any solution?

**Comment by chengsieuly** [comment]
Hmm, currently, custom sounds does not affect the notification sound. They are meant to replace the default ticking played during each phase. Did you mean that this is not working for you?

**Comment by chengsieuly** [comment]
@freekarol, I was a little confused here. You prefer a way to change the notification sound (during phase changes) also?
