### ISSUE TITLE
Pause and resume buttons should be combined

### ISSUE THREAD

**Issue by allenfrostline** [builtwithluv/ZenFocus#257]
See below. Pausing and resuming should not be available at the same time. As far as I'm concerned, it's supposed to be "pause" by default and once it's pausing, "resume". Am I right?

<img width="182" alt="screen shot 2018-06-09 at 12 16 38 pm" src="https://user-images.githubusercontent.com/24261329/41190456-0b153c46-6bdf-11e8-8623-393e70696e66.png">

**Comment by chengsieuly** [comment]
Definitely agree. I'll make update soon and thanks for using!

**Comment by chengsieuly** [comment]
Can't figure this out - seems to bea
