### ISSUE TITLE
Preference setting to hide menu bar icon

### ISSUE THREAD

**Issue by gprasant** [builtwithluv/ZenFocus#258]
<img width="276" alt="screen shot 2018-08-22 at 1 06 59 pm" src="https://user-images.githubusercontent.com/212911/44487898-47d8a980-a60c-11e8-9444-9dec3192675a.png">

Currently, when the Zen Focus app is running, it adds its icon to the menu bar. This has some problems. 

1. It takes away precious menu bar space. 
2. The timer with seconds is distracting. 
3. Cmd + dragging the icon off the menu bar does not make it disappear.

It would be great if it was possible to configure whether this menu bar icon is visible.

**Comment by gprasant** [comment]
@chengsieuly

**Comment by gprasant** [comment]
ping again :-)

**Comment by ehguo** [comment]
Lol it's been so long since I worked on this, I'll see if I can take a look this weekend if Cheng doesn't.

**Comment by chengsieuly** [comment]
That's a good idea @gprasant. Thanks @ehguo . If you want to pull this in, please feel free. If not, I can take this on next week. Got a day off lol.

**Comment by chengsieuly** [comment]
@gprasant Work is done and now I need to fix a couple more things before I release next version 👍
