### ISSUE TITLE
Bad UI in Windows compact mode

### ISSUE THREAD

**Issue by chengsieuly** [builtwithluv/ZenFocus#60]
Requirements:
- Add more space ONLY for windows
- Other option is to remove the title bar for windows too
<img width="121" alt="capture" src="https://cloud.githubusercontent.com/assets/10070358/26794831/1cdbcdca-49d8-11e7-8caf-d1989971468d.PNG">
<img width="122" alt="capture2" src="https://cloud.githubusercontent.com/assets/10070358/26794832/1ce3fce8-49d8-11e7-9fa6-511036439e00.PNG">

**Comment by ehguo** [comment]
Will change app to be frameless window, but will need custom menus on Windows OS

**Comment by chengsieuly** [comment]
Okay, frameless does look 10x better so let's do that. Window users will be happy to receive a customized menu bar and not the default look haha
